spring.application.name=api
# Neon Bulut Veritabanı Bağlantısı
spring.datasource.url=jdbc:postgresql://ep-sparkling-shape-axpu5w7c.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4JEuAzn2pBHO

# Hibernate / JPA Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true